from mcp.server.fastmcp import FastMCP
from typing import Optional
import sys
import os

# Import our internal modules
# We need to ensure we can import from src/airflow_net if running as module
# But standard import should work if package is installed in editable mode or PYTHONPATH set
from airflow_net.agent import AirflowAgent
from airflow_net.server_manager import ensure_server_running

# Initialize FastMCP
mcp = FastMCP("airflow-net")

@mcp.tool()
def generate_airflow_dag(instruction: str, airflow_version: str = "2.7.2") -> str:
    """
    Generates an Airflow DAG based on the instruction using the local specialized model.
    
    Args:
        instruction: Desired DAG behavior (e.g. "Fetch data from API every hour")
        airflow_version: Target Airflow version (default: 2.7.2)
    """
    
    # 1. Auto-start backend if needed (lazy loading)
    try:
        # We rely on defaults or env var set by CLI
        default_url = "http://localhost:8000/v1"
        server_url = os.environ.get("AIRFLOW_NET_SERVER_URL", default_url)
        
        ensure_server_running(url=server_url)
    except Exception as e:
        return f"System Error: Failed to start inference backend: {e}"
    
    # 2. Delegate to Agent
    try:
        agent = AirflowAgent(server_url=server_url)
        result = agent.generate_dag(instruction, airflow_version)
        
        if result["success"]:
            # Clean up the output to be just code if possible, or return full markdown
            attempts = result.get("attempts", 1)
            code = result["code"]
            
            # Prepend metadata for the LLM
            header = f"# Generated by Airflow-Net (Success after {attempts} attempts)\n# Validation Status: PASS\n"
            if attempts > 1:
                header += f"# Note: Self-correction was applied {attempts-1} times to fix syntax errors.\n"
            
            return header + "\n" + code
        else:
            errors = result.get("errors", [])
            return f"Generation Failed. Validation Errors:\n" + "\n".join(f"- {e}" for e in errors)
            
    except Exception as e:
        return f"Agent Error: {e}"

if __name__ == "__main__":
    mcp.run()
